### ISSUE TITLE
leader 00

### ISSUE THREAD

**Issue by tegk** [dongri/phonenumber#4]
Why does it not work when the prefix is 00 instead of +?
```

number := phonenumber.Parse("0044 7522 853519", "")
	fmt.Println(number)
```

`2019/08/29 14:31:36 the phone number supplied is not a number`

**Comment by 4rakcheev** [comment]
First of all, the second param (country) must be set properly, otherwise, the USA country will be used.
But if you set a country and pass a number with leader 00, the result  be correct:
```
func main() {
	fmt.Printf("parsed=%s\n", phonenumber.Parse("+44 7522 853519", ""))
	fmt.Printf("parsed=%s\n", phonenumber.Parse("0044 7522 853519", ""))
	fmt.Printf("parsed=%s\n", phonenumber.Parse("+44 7522 853519", "gb"))
	fmt.Printf("parsed=%s\n", phonenumber.Parse("0044 7522 853519", "gb"))
}
```

```
parsed=447522853519
parsed=
parsed=447522853519
parsed=447522853519
```
https://play.golang.org/p/jNtE29hMILk

btw, the issue is: for `phonenumber.Parse("+44 7522 853519", "usa")` must be empty, not the Britain number `447522853519`.
